--- 
title: "Libro de prueba"
author: 'Karina A. '
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  Este es un libro para facilitar la vida
link-citations: yes
github-repo: "rstudio/bookdown-demo"
---

# Sobre el curso

Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. 


## Parte 1 

Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.

## Consideraciones

Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.

## Otros

Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito. Pablito clavó un clavito.


